"""add deleted_at for soft delete

Revision ID: 658b21298782
Revises: f8242b498188
Create Date: 2026-06-15 12:17:48.998027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '658b21298782'
down_revision: Union[str, None] = 'f8242b498188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'deleted_at')
    op.drop_column('diets', 'deleted_at')
    # ### end Alembic commands ###
