"""add diet_reminders

Revision ID: 68f37ec7c532
Revises: 1d20b1323eed
Create Date: 2026-06-16 16:57:33.591766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '68f37ec7c532'
down_revision: Union[str, None] = '1d20b1323eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
