"""add diet_reminders

Revision ID: 68f37ec7c532
Revises: 1d20b1323eed
Create Date: 2026-06-16 16:57:33.591766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '68f37ec7c532'
down_revision: Union[str, None] = '1d20b1323eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diet_reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("diet_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("intake_link_id", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_to_email", sa.String(length=190), nullable=False),
        sa.ForeignKeyConstraint(["diet_id"], ["diets.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"]),
        sa.ForeignKeyConstraint(["intake_link_id"], ["patient_intake_links.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_diet_reminders_id"), "diet_reminders", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diet_reminders_id"), table_name="diet_reminders")
    op.drop_table("diet_reminders")
    # ### end Alembic commands ###
